seed: 234

n_hidden_dense_lower_output: 5
n_hidden_dense_lower: 1000
n_hidden_dense_upper: 100
n_hidden_conv: 100
n_layers_conv: 6
n_layers_dense_lower: 6
n_layers_dense_upper: 4

spatial_width: 28
n_temporal_basis: 20

trajectory_length: 700
n_colours: 1

learning_rate:  0.001
batch_size: 200
steps: 2

model_save_name: "mnist_better_hyparameters.ex"
